# Generated by Django 3.2.12 on 2022-10-27 20:29

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(null=True, verbose_name="Birth Date")),
                ("iin", models.CharField(max_length=12, verbose_name="IIN")),
                (
                    "doctor_id",
                    models.PositiveIntegerField(default=0, verbose_name="Doctor ID"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("surname", models.CharField(max_length=32, verbose_name="Surname")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Middle name"
                    ),
                ),
                (
                    "department_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Department ID"
                    ),
                ),
                (
                    "specialization_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Specialization ID"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Experience in Years"
                    ),
                ),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="doctor/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Higest"), (1, "First"), (2, "Second")],
                        verbose_name="Category",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Price of Appointment"
                    ),
                ),
                (
                    "schedule_details",
                    models.CharField(max_length=256, verbose_name="Schedule Details"),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[("MD", "Md"), ("PHD", "Phd")],
                        max_length=3,
                        verbose_name="Education",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Rating"),
                ),
                ("address", models.CharField(max_length=64, verbose_name="Address")),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(null=True, verbose_name="Birth Date")),
                ("iin", models.CharField(max_length=12, verbose_name="IIN")),
                (
                    "patient_id",
                    models.PositiveIntegerField(default=0, verbose_name="Patient ID"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("surname", models.CharField(max_length=32, verbose_name="Surname")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Middle name"
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("O", "O"), ("AB", "Ab")],
                        max_length=2,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(
                        max_length=8, verbose_name="Emergency Contact Number"
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=12, verbose_name="Contact Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                ("address", models.CharField(max_length=64, verbose_name="Address")),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("s", "Single"), ("m", "Married"), ("d", "Divorced")],
                        max_length=1,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(null=True, verbose_name="Registration Field"),
                ),
            ],
        ),
    ]
