# Generated by Django 3.2.12 on 2022-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221203_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
